### ISSUE TITLE
GPU RAM

### ISSUE THREAD

**Issue by algoterranean** [ayanc/mdepth#1]
Good afternoon. First, let me say, great work!

I was wondering, is there any way to run this on an 8GB card (e.g. NVIDIA 1070 GTX)? Or would anyone have any suggestions as to how it could be done?

Thanks!

**Comment by ayanc** [comment]
Not directly. To make things fit on a GPU with less memory, you'll probably need to make (probably major) edits to the code that a) for the neural network pass, applies the network on sub-crops of the image and assembles everything back on the CPU, b) for the globalization part, copies things between back and forth between the CPU and GPU within each iterations. This will obviously come at a cost in terms of running time.

**Comment by algoterranean** [comment]
Thanks, Ayan. I was able to get ahold of a K40 and, after some small modifications (involving fft), got it to just fit. Very impressive results!

Out of curiosity, what card did the three of you use and what version of Matlab? The K40 with 2016b ended up being about maybe, I'm guessing, 200MB shy of working out of the box. 

Thanks, Patrick

**Comment by ayanc** [comment]
We tried this with a Titan X and Matlab R2015b.

**Comment by algoterranean** [comment]
Thank you very much.
