### ISSUE TITLE
Official train test split

### ISSUE THREAD

**Issue by JonathanCMitchell** [ayanc/mdepth#5]
Hi there, you mentioned that you used the "official train test split" for the NYUV2 dataset. What is the official train test split? Do you happen to know where I can find any information about which videos to use for training, and which for testing? Thanks

**Comment by ayanc** [comment]
https://cs.nyu.edu/~silberman/projects/indoor_scene_seg_sup.html --- contains official train/test split for the 'labeled' dataset. The labeled dataset is a small number of frames from the full RAW dataset. You can lookup what the videos the official 'test' frames came from, and make sure you don't use **any** frame from those videos for training.
